services:
  - type: static
    name: gramzo-frontend
    env: static
    buildCommand: npm install && npm run build
    publishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
